### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by Kr4is** [gpul-school/school2018-2019#1]
Charla/taller sobre las nociones básicas de git como control de versiones.

**Comment by SaulEiros** [comment]
Temas a tratar:
- Que es git y los controladores de versiones.
- Que aspectos mejora ante otros controladores.
- Quien ofrece este servicio.
- Gitlab FIC.
- Aspectos Básicos desde web y terminal.

Nota: Tratar hasta ramas, comentarlo pero no abordarlo.
