### ISSUE TITLE
Introducción a Latex

### ISSUE THREAD

**Issue by SaulEiros** [gpul-school/school2018-2019#10]
Charla introductoria a Latex

**Comment by SaulEiros** [comment]
- Que es Latex y sus ventajas.
- Instalar latex y sus distintos editores.
- Sentencias básicas de Latex: Cabeceras, listas, referencias, imagenes y organización del propio documento.

**Comment by braisarias** [comment]
Esta charla propoño realizala cando se achegue a data dos TFG/TFM. Maio ou por aí?
Con algún título encamiñado a os TFG e TFM
