### ISSUE TITLE
Hardware Libre

### ISSUE THREAD

**Issue by Kr4is** [gpul-school/school2018-2019#9]

**Comment by SaulEiros** [comment]
- Que es el hardware libre con ejemplos.
- Raspberry, conceptos básicos y características.
- Pequeño taller introductorio.

**Comment by braisarias** [comment]
Eu máis que raspberry propondría arduino e similares.
Obviamente ofrézome como voluntario a dar unha charla introdutoria a o que é hardware libre e a arduino. Pero faríao en plan obradoiro, se vos parece, podería seguir un esquema algo así:
* Que é o hardware libre
* Exemplos de hardware libre e contraexemplos
* Introdución á plataforma Arduino
* Exercicios práticos básicos de Arduino
* Exemplos do que se pode facer coa plataforma Arduino: escornabots, impresoras 3D...

Podedes ver unha mostra do obradoiro que demos hai tempo nos GPUL Labs:
https://github.com/braisarias/obradoiro-arduino
